### ISSUE TITLE
Heroku Auto Deploy - problem with mailgun

### ISSUE THREAD

**Issue by FundreasFrohsinn** [zonque/AlRide#7]
Since mailgun has changed their sandbox subdomain policy it doesn't seem to be working without having an own server to set up for this:
https://help.mailgun.com/hc/en-us/articles/217531258
from the logs:
"Net::SMTPFatalError (554 Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in domain settings."

Is there a simple work around or alternative?

**Comment by zonque** [comment]
Don't know what to do about that. Unrestricted access to outgoing mail facilities is always a problem. Is setting up a Mailgun server not an option for you? Is there any other service you would prefer over this?
